#!/bin/bash

read -p "Type the wanted codename here:  " codename
read -p "Type location or just the name of program here:  " cscript
gcc -o $codename $cscript -lm
echo "<==================OUTPUT OF C PROGRAM w/ -lm option==================>"
echo
~/c_programs/$codename
