#!/bin/bash

chmod +x ~/bin/* ~/python_programs/* ~/c_programs/*
sudo sed -i "1i\bash ~/bin/copyConfig" /etc/profile
sudo sed -i "1i\bash ~/bin/todo" $HOME/.bashrc
sudo sed -i "\$a export PATH=$PATH:$HOME/bin:$HOME/c_programs:$HOME/python_programs" $HOME/.bashrc
sudo cp ~/config/.hyper.js ~/
sudo sed -i "bind -x '"\C-g":$HOME/python_programs/gitPushAll.py'" $HOME/.bashrc
