#!/bin/bash

mkdir /home/$USER/logs #used for storing user logs

cd /home/$USER/
mv /home/$USER/bash /home/$USER/bin
git clone https://github.com/zigjag/c_programs.git
git clone https://github.com/zigjag/python_programs.git
git clone https://github.com/zigjag/config.git

mkdir /home/$USER/Github; cd /home/$USER/Github
git clone https://github.com/zigjag/Programmapedia.git
git clone https://github.com/zigjag/Wiki-API.git
git clone https://github.com/zigjag/budgetCrud.git

bash /home/$USER/bin/configSetup
