#!/bin/bash

cd ~/
mv ~/bash ~/bin
git clone https://github.com/zigjag/c_programs.git
git clone https://github.com/zigjag/python_programs.git
git clone https://github.com/zigjag/config.git

mkdir ~/Github; cd ~/Github
git clone https://github.com/zigjag/Programmapedia.git
git clone https://github.com/zigjag/Wiki-API.git
git clone https://github.com/zigjag/budgetCrud.git

bash ~/bin/configSetup
