#!/bin/bash
git config --global user.email "jkligel@gmail.com"
git config --global user.name "Joseph Kligel"

git add . --all 
git commit -m "Using bash script to push all updates" 
git push -u origin master 
