#!/bin/bash

cd ~/bin && git pull
cd ~/python_programs && git pull
cd ~/c_programs && git pull
cd ~/config && git pull

cd ~/Github/Programmapedia && git pull
cd ~/Github/budgetCrud && git pull
cd ~/Github/securitynode && git pull
cd ~/Github/blog && git pull
cd ~/Github/Wiki-API && git pull
