#!/bin/bash

sudo apt update

sudo apt install gcc -y 
sudo apt install python3 -y
sudo apt install node -y
sudo apt install npm -y
sudo npm i -g nodemon lodash -y
sudo apt install mysql -y
sudo apt install mongodb -y #check to see if it works

sudo apt install vlc
