#!/bin/bash

sudo apt update

sudo apt install dpkg curl wget gcc python3 node git -y
sudo apt install npm -y
sudo npm i -g nodemon lodash heroku -y
sudo apt install mongodb mongodb-clients mongodb-server-core mysql-server -y
sudo apt install vlc audacious skype uget dropbox -y
sudo apt install gnome-tweaks wine caffeine libreoffice gimp -y
sudo apt install nano emacs nautilus xterm -y
sudo apt install snapd -y
sudo snap install atom --classic
sudo snap install spotify wine -y
sudo apt install qbittorrent calibre 7zip unzip -y
sudo apt install gparted virtualbox gimp pidgin -y
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install ./google-chrome-stable_current_amd64.deb -y

wget https://releases.hyper.is/download/deb
sudo dpkg -i ./deb
sudo apt install gdebi -y
wget https://hyper-updates.now.sh/download/linux_deb
sudo gdebi ./linux_deb
hyper i hypercwd && hyper i hyperpower && hyper i hyper-pane && hyper i hyperterm-dibdabs && hyper i hyper-savetext

sudo apt-get install gnome-shell -y
sudo apt-get install ubuntu-gnome-desktop -y

echo "deb https://deb.etcher.io stable etcher" | sudo tee /etc/apt/sources.list.d/balena-etcher.list
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61
sudo apt-get install balena-etcher-electron

bash $HOME/bin/updatedeb
