#!/bin/bash

echo "Installing gnome-extensions-app..."
sudo dnf install -y gnome-extensions-app"

echo ""

echo "Installing caffeine..."
git clone git://github.com/eonpatapon/gnome-shell-extension-caffeine.git
cd gnome-shell-extension-caffeine
./update-locale.sh
glib-compile-schemas --strict --targetdir=caffeine@patapon.info/schemas/ caffeine@patapon.info/schemas
cp -r caffeine@patapon.info ~/.local/share/gnome-shell/extensions

echo ""

echo "Enable caffeine extension"
gnome-extensions-app
