#!/usr/bin/sh

sudo pacman -Syu -y
pacman -S nodejs atom vim nano python python-pip npm nvm apm gcc
sudo pacman -S dpkg curl wget gcc python3 node git -y
sudo pacman -S qemu kvm -y
sudo npm i -g nodemon lodash heroku -y
sudo pacman -S mongodb mongodb-clients mongodb-server-core mysql-server -y
sudo pacman -S vlc audacious skype uget dropbox -y
sudo pacman -S gnome-desktop gnome-tweaks wine caffeine libreoffice gimp -y
sudo pacman -S nano emacs nautilus xterm -y
sudo pacman -S snapd -y
sudo pacman -S qbittorrent calibre 7zip unzip -y
sudo pacman -S gparted virtualbox gimp pidgin -y
sudo pacman -S google-chrome
sudo pacman -S-get gnome-shell -y
sudo pacman -S-get ubuntu-gnome-desktop -y
sudo pacman -S balena-etcher-electron
