#!/bin/bash

sudo dnf update
sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
sudo dnf install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
sudo dnf install vlc python-vlc unzip nano emacs -y
sudo dnf install icedtea-web java-openjdk wine -y
sudo dnf install gimp pidgin qbittorrent simple-scan mediawriter libappindicator xterm gnome-terminal snapd-y
sudo ln -s /var/lib/snapd/snap /snap
sudo dnf install lpf-spotify-client
sudo dnf config-manager --add-repo=http://negativo17.org/repos/fedora-steam.repo
sudo dnf config-manager --add-repo=http://negativo17.org/repos/fedora-spotify.repo

sudo dnf install emacs -y
sudo dnf install gcc -y
sudo dnf install python3 -y
sudo dnf install nano -y
sudo dnf install node npm -y
sudo npm i -g nvm nodemon lodash heroku
sudo dnf install $(curl -sL "https://api.github.com/repos/atom/atom/releases/latest" | grep "https.*atom.x86_64.rpm" | cut -d '"' -f 4) -y
sudo dnf install mysql -y

sudo echo "fastestmirror=true" >> /etc/dnf/dnf.conf

sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
sudo dnf copr enable kwizart/fedy
sudo dnf install fedy -y

echo "Finished. Don't forget to install hyper.is, add message to /etc/yum.repos.d/mongodb-org-4.2.repo and uncomment line 28 to install mongodb." 



